### PR TITLE
Changes saving configuration from locale to handle for multi site

### PR DESCRIPTION
**Pull request by quintenbuis**
This MR changes the way the configuration is saved. Instead of saving to locale it uses the site handle. This enables the ability to configure different cookies for each site in Statamic.

This MR is a proposal. Would love to hear the original authors thoughts and remarks on this approach.

### CODE REVIEW

**Comment by quintenbuis** [comment]
@dryven-dano What do you think of this MR? Would love if this could make it in the repo!

**Comment by dryven-dano** [comment]
Hey @quintenbuis, I had a quick look at the code and it looks fine. I have the following questions:

1. What are the exact values of `Site::current()->locale()` and `Site::current()->handle()` with a specific example?
2. Would that be backwards-compatible with the config file from before?

If the backwards compatibility could be provided, then I'd gladly merge this PR as it's a good idea! Could you check that?

Thank you for the PR,
Cheers,
Dano.

**Comment by quintenbuis** [comment]
> What are the exact values of Site::current()->locale() and Site::current()->handle() with a specific example?

If were looking at the site configuration of Statamic we can see the following:
```php
    // The keys will be used by Site::current()->handle().
    'foo' => [
        'name' => 'foo.com',
        'slug' => 'foo_com',
        'locale' => 'nl_NL', // This value will be used by Site::current()->locale().
        'url' => 'https://foo.com',
        'origin' => null,
    ],
    
    'bar' => [
        'name' => 'bar.com',
        'slug' => 'bar_com',
        'locale' => 'nl_NL',
        'url' => 'https://bar.com',
        'origin' => null,
    ],
```
The locale is the same for each site and thus creating overlap between the sites. To be able to configure the sites separate from each other we need to look at the handle for uniqueness.

> Would that be backwards-compatible with the config file from before?

I could definitely make this backwards compatible by providing an option in the config file. Will add this later today!

**Review by dryven-dano — APPROVED** [review]
Hey Quinten!

Sorry, I was a little busy last week. Thanks for the changes and making it backwards compatible. Looks awesome. I'll merge it for the next release that'll be happening this week. Love the feature 😃 

Cheers,
Dano.

**Pull request merged**
